# Generated by Django 3.1.7 on 2021-03-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('workHistory', models.TextField()),
                ('blog', models.URLField()),
                ('kakaoTalk', models.FileField(upload_to='')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
